# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ganesa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ganesa

  target 'Ganesa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GanesaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Ganesa-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ganesa-tvOS

  target 'Ganesa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
