# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Ganesa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

   react_native_path = "../node_modules/react-native"
    pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga"
    pod "React", :path => react_native_path, :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
    ]

    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Firestore'

  # Pods for Ganesa

  target 'GanesaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Ganesa-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ganesa-tvOS

  target 'Ganesa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
